var Config = {
	api: {
		//endPoint : "http://chchedu.herokuapp.com/api/"
		endPoint : "http://172.16.1.52:9010/api/"
	},
	slug: {
		login : "admin/login",
		createBusiness : "business/create",
		updateBusiness : "business/update",
		getBusiness : "business/get",
		deleteBusiness : "business/delete",

		createBusinessCategory : "category/create",
		updateBusinessCategory : "category/update",
		getBusinessCategory : "category/get",
		deleteBusinessCategory : "category/delete",

		createDeal : "deal/create",
		updateDeal : "deal/update",
		getDeal : "deal/get",
		deleteDeal : "deal/delete",

		createDealCategory : "deal_category/create",
		updateDealCategory : "deal_category/update",
		getDealCategory : "deal_category/get",
		deleteDealCategory : "deal_category/delete",

		createEvent : "event/create",
		updateEvent : "event/update",
		getEvent : "event/get",
		deleteEvent : "event/delete",

		createEventCategory : "event_category/create",
		updateEventCategory : "event_category/update",
		getEventCategory : "event_category/get",
		deleteEventCategory : "event_category/delete",

		createGuide : "guide/create",
		updateGuide : "guide/update",
		getGuide : "guide/get",
		deleteGuide : "guide/delete",

		createGuideCategory : "guide_category/create",
		updateGuideCategory : "guide_category/update",
		getGuideCategory : "guide_category/get",
		deleteGuideCategory : "guide_category/delete",

		createAmbassador : "ambassador/create",
		updateAmbassador : "ambassador/update",
		getAmbassador : "ambassador/get",
		deleteAmbassador : "ambassador/delete",

		createUser : "user/create",
		updateUser : "user/update",
		getUser : "user/get",
		deleteUser : "user/delete",

		getStats : "stats/get",
		deleteUser : "user/delete",
	}
}

var Nationality = ["Afghan",
				"Albanian",
				"Algerian",
				"Andorran",
				"Angolan",
				"Argentinian",
				"Armenian",
				"Australian",
				"Austrian",
				"Azerbaijani",
				"Bahamian",
				"Bangladeshi",
				"Barbadian",
				"Belorussian",
				"Belgian",
				"Beninese",
				"Bhutanese",
				"Bolivian",
				"Bosnian",
				"Brazilian",
				"Briton",
				"Bruneian",
				"Bulgarian",
				"Burmese",
				"Burundian",
				"Cambodian",
				"Cameroonian",
				"Canadian",
				"Chadian",
				"Chilean",
				"Chinese",
				"Colombian",
				"Congolese",
				"Croatian",
				"Cuban",
				"Cypriot",
				"Czech",
				"Dane",
				"Dominican",
				"Ecuadorean",
				"Egyptian",
				"Salvadorean",
				"Englishman",
				"Eritrean",
				"Estonian",
				"Ethiopian",
				"Fijian",
				"Finn",
				"Frenchman",
				"Gabonese",
				"Gambian",
				"Georgian",
				"German",
				"Ghanaian",
				"Greek",
				"Grenadian",
				"Guatemalan",
				"Guinean",
				"Guyanese",
				"Haitian",
				"Dutchman",
				"Honduran",
				"Hungarian",
				"Icelander",
				"Indian",
				"Indonesian",
				"Iranian",
				"Iraqi",
				"Irishman",
				"Israeli",
				"Italian",
				"Jamaican",
				"Japanese",
				"Jordanian",
				"Kazakh",
				"Kenyan",
				"Korean",
				"Kuwaiti",
				"Laotian",
				"Latvian",
				"Lebanese",
				"Liberian",
				"Libyan",
				"Liechtensteiner",
				"Lithuanian",
				"Luxembourger",
				"Macedonian",
				"Madagascan",
				"Malawian",
				"Malaysian",
				"Maldivian",
				"Malian",
				"Maltese",
				"Mauritanian",
				"Mauritian",
				"Mexican",
				"Moldovan",
				"Monacan",
				"Mongolian",
				"Montenegrin",
				"Moroccan",
				"Mozambican",
				"Namibian",
				"Nepalese",
				"New Zealander",
				"Nicaraguan",
				"Nigerien",
				"Nigerian",
				"Norwegian",
				"Pakistani",
				"Panamanian",
				"Paraguayan",
				"Peruvian",
				"Filipino",
				"Pole",
				"Portuguese",
				"Qatari",
				"Romanian",
				"Russian",
				"Rwandan",
				"Saudi",
				"Scot",
				"Senegalese",
				"Serbian",
				"Singaporean",
				"Slovak",
				"Slovenian",
				"Somali",
				"Spaniard",
				"Sri Lankan",
				"Sudanese",
				"Surinamese",
				"Swazi",
				"Swede",
				"Swiss",
				"Syrian",
				"Taiwanese",
				"Tadzhik",
				"Tanzanian",
				"Thai",
				"Togolese",
				"Trinidadian",
				"Tunisian",
				"Turk",
				"Ugandan",
				"Ukrainian",
				"British",
				"American",
				"Uruguayan",
				"Uzbek",
				"Venezuelan",
				"Vietnamese",
				"Welshman",
				"Yemeni",
				"Yugoslav",
				"Zambian",
				"Zimbabwean"];